name: glacier-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10  # Specify your preferred Python version
  - pip
  - numpy
  - pandas
  - geopandas
  - gdal
  - rasterio
  - pyproj
  - rioxarray
  - xarray
  - folium
  - fiona
  - matplotlib
  - shapely
  - h5py
  - opencv
  - scikit-image>=0.19,<0.20.0  # Adjust version as needed
  - scipy
  - descartes
  - numba
  - jupyter
  - sphinx-argparse
  - pyvips
  - ipykernel  # Allows kernel registration for VSCode/Jupyter
  - wget
  - pip:
      - llc
      - pybob
      - earthaccess
      - rasterstats
      - git+https://github.com/dshean/pygeotools.git # these links correspond to the packages necessary for DEM coregistration
      - git+https://github.com/dshean/demcoreg.git
      - git+https://github.com/dshean/imview.git
